steps:
  #build docker image in target project with git commit tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/dash-cloudrun-demo:${SHORT_SHA}", "."]

    #push docker image with git commit to container registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/dash-cloudrun-demo"]

    #gcloud command to deploy newly built image to cloud run, must set cloudbuild service account with Cloud Run Admin role
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "dash-cloudrun-demo",
        "--image",
        "gcr.io/$PROJECT_ID/dash-cloudrun-demo:${SHORT_SHA}",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

images: ["gcr.io/$PROJECT_ID/dash-cloudrun-demo"] #save image to google container registry
