steps:
  - name: "gcr.io/cloud-builders/docker" #build docker image in target project with tag
    args: ["build", "-t", "gcr.io/$PROJECT_ID/dash-demo:test", "."]

  - name: "gcr.io/cloud-builders/gcloud" #gcloud command to deploy newly built image to cloud run, must set cloudbuild service account with Cloud Run Admin role
    args:
      [
        "beta",
        "run",
        "deploy",
        "cloudrun-demo",
        "--image",
        "gcr.io/$PROJECT_ID/dash-demo:test",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/$PROJECT_ID/dash-demo" #save image to google container registry
