project = "jb-demo-209016"
service_account_email = "jb-iotdemo@jb-demo-209016.iam.gserviceaccount.com"
startup_script_username = "johnbacon@cloudshell.com"
github_owner = "anonwhois"
github_branch_name = "master"
